export interface SourceCodeFile {
  filename: string;
  language: "charp" | "sql" | "xml" | "javascript" | "css" | "markdown";
  titleHe: string;
  titleEn: string;
  descriptionHe: string;
  descriptionEn: string;
  code: string;
}

export const dotNetSourceCode: SourceCodeFile[] = [
  {
    filename: "Supabase_Schema_and_Procedures.sql",
    language: "sql",
    titleHe: "סקריפט סכימה לפלטפורמת Supabase (PostgreSQL)",
    titleEn: "Supabase PostgreSQL Database Schema",
    descriptionHe: "תרגום מלא, תקין ואופטימלי לכל הטבלאות, אינדקסים, מפתחות זרים, פונקציות PL/pgSQL, ומדיניות אבטחת שורות (RLS) המתאים לשימוש ישיר ב-Supabase SQL Editor.",
    descriptionEn: "Flawless and complete translated PostgreSQL schema for direct paste into Supabase SQL Editor. Fully compliant with modern Postgres standard types, PL/pgSQL routines, and Row-Level Security (RLS) policies.",
    code: `-- ====================================================================================
-- SYSTEM: Agricultural Research Center Warehouse Request Management System
-- INTEGRATION: Supabase.com / PostgreSQL Database Schema & Relationships Script
-- DESIGNED FOR: PostgreSQL 14+ (Compatible with modern Supabase projects)
-- CRITICAL TRANSLATION CHECKS:
--   1. IDENTITY(1,1)   ==> GENERATED BY DEFAULT AS IDENTITY (Identity SQL-standard columns)
--   2. NVARCHAR(x)     ==> VARCHAR(x) or TEXT
--   3. DATETIME        ==> TIMESTAMPTZ (Timezone aware timestamps)
--   4. BIT             ==> BOOLEAN (True/False values)
--   5. GETDATE()       ==> NOW()
--   6. OPENJSON()      ==> jsonb_array_elements_text() / jsonb functions
--   7. MERGE / CATCH   ==> INSERT INTO ... ON CONFLICT (Native Postgres Upserts)
-- ====================================================================================

-- ====================================================================================
-- 0. PRE-FLIGHT INITIAL SETUP
-- ====================================================================================

-- Set local search path
SET search_path TO public;

-- Enable UUID helpers just in case for primary keys extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ====================================================================================
-- 1. SCHEMAS & TABLES DEFINITIONS
-- ====================================================================================

-- A. AttributeTypes Table (Size, Color, Model...)
CREATE TABLE IF NOT EXISTS AttributeTypes (
    AttributeTypeId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TypeNameEn VARCHAR(100) NOT NULL UNIQUE,
    TypeNameHe VARCHAR(100) NOT NULL UNIQUE,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedDate TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CreatedBy VARCHAR(100) NOT NULL
);

-- Index for live Active query optimization
CREATE INDEX IF NOT EXISTS IX_AttributeTypes_Active_Deleted 
ON AttributeTypes (IsActive, IsDeleted) 
INCLUDE (TypeNameEn, TypeNameHe);


-- B. AttributeValues Table (S, M, L, Red, Blue...)
CREATE TABLE IF NOT EXISTS AttributeValues (
    AttributeValueId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AttributeTypeId INT NOT NULL,
    ValueNameEn VARCHAR(100) NOT NULL,
    ValueNameHe VARCHAR(100) NOT NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedDate TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CreatedBy VARCHAR(100) NOT NULL,
    
    -- Foreign key to parent attribute type with cascading deletions
    CONSTRAINT FK_AttributeValues_AttributeTypes FOREIGN KEY (AttributeTypeId) 
        REFERENCES AttributeTypes (AttributeTypeId) ON DELETE CASCADE,
        
    -- Unique constraint preventing duplicate entries within the same category
    CONSTRAINT UQ_AttributeValue_Type_Name UNIQUE (AttributeTypeId, ValueNameHe)
);

-- Index for selector optimization
CREATE INDEX IF NOT EXISTS IX_AttributeValues_TypeId_Active 
ON AttributeValues (AttributeTypeId, IsActive, IsDeleted)
INCLUDE (ValueNameHe, ValueNameEn);


-- C. WarehouseItems Table (Extended Items Catalog)
CREATE TABLE IF NOT EXISTS WarehouseItems (
    SKU VARCHAR(50) PRIMARY KEY,
    NameHe VARCHAR(200) NOT NULL,
    NameEn VARCHAR(200) NOT NULL,
    Stock INT NOT NULL DEFAULT 0,
    Price DECIMAL(18, 2) NOT NULL DEFAULT 0.0,
    Shelf VARCHAR(50) NULL,
    CategoryHe VARCHAR(100) NULL,
    CategoryEn VARCHAR(100) NULL,
    UnitHe VARCHAR(50) NULL,
    UnitEn VARCHAR(50) NULL,
    ImageUrl TEXT NULL,
    ImageFilter VARCHAR(100) NULL
);


-- D. ItemPictureUrls Table (Product Image Attachments)
CREATE TABLE IF NOT EXISTS ItemPictureUrls (
    PictureId VARCHAR(100) PRIMARY KEY,
    SKU VARCHAR(50) NOT NULL,
    ImageUrl TEXT NOT NULL,
    ImageSource VARCHAR(100) NOT NULL,
    IsPrimary BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedDate TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UpdatedDate TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CreatedBy VARCHAR(100) NOT NULL,
    UpdatedBy VARCHAR(100) NOT NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT FK_ItemPictureUrls_SKU FOREIGN KEY (SKU)
        REFERENCES WarehouseItems (SKU) ON DELETE CASCADE
);


-- E. ItemAttributeMapping (Maps Attribute Type to SKU)
CREATE TABLE IF NOT EXISTS ItemAttributeMapping (
    SKU VARCHAR(50) NOT NULL,
    AttributeTypeId INT NOT NULL,
    IsMandatory BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedDate TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CreatedBy VARCHAR(100) NOT NULL,
    
    PRIMARY KEY (SKU, AttributeTypeId),
    CONSTRAINT FK_ItemAttributeMapping_AttributeTypes FOREIGN KEY (AttributeTypeId)
        REFERENCES AttributeTypes (AttributeTypeId),
    CONSTRAINT FK_ItemAttributeMapping_SKU FOREIGN KEY (SKU)
        REFERENCES WarehouseItems (SKU) ON DELETE CASCADE
);


-- F. ItemAttributeAllowedValues (Whitelisted Attribute Values Allowed For Specific SKU)
CREATE TABLE IF NOT EXISTS ItemAttributeAllowedValues (
    SKU VARCHAR(50) NOT NULL,
    AttributeTypeId INT NOT NULL,
    AttributeValueId INT NOT NULL,
    
    PRIMARY KEY (SKU, AttributeTypeId, AttributeValueId),
    
    CONSTRAINT FK_ItemAttributeAllowedValues_Mapping FOREIGN KEY (SKU, AttributeTypeId)
        REFERENCES ItemAttributeMapping (SKU, AttributeTypeId) ON DELETE CASCADE,
        
    CONSTRAINT FK_ItemAttributeAllowedValues_Value FOREIGN KEY (AttributeValueId)
        REFERENCES AttributeValues (AttributeValueId)
);


-- G. WarehouseRequests Table (Issuance Request Tracking)
CREATE TABLE IF NOT EXISTS WarehouseRequests (
    RequestId VARCHAR(50) NOT NULL,
    SKU VARCHAR(50) NOT NULL,
    ItemNameHe VARCHAR(200) NOT NULL,
    ItemNameEn VARCHAR(200) NOT NULL,
    QuantityRequested INT NOT NULL,
    AttributeTypeId INT NULL,
    AttributeValueId INT NULL,
    RequestDate TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    RequestedBy VARCHAR(100) NOT NULL,
    StatusHe VARCHAR(50) NOT NULL,
    StatusEn VARCHAR(50) NOT NULL,

    PRIMARY KEY (RequestId, SKU),
    CONSTRAINT FK_WarehouseRequests_SKU FOREIGN KEY (SKU)
        REFERENCES WarehouseItems (SKU),
    CONSTRAINT FK_WarehouseRequests_Type FOREIGN KEY (AttributeTypeId)
        REFERENCES AttributeTypes (AttributeTypeId),
    CONSTRAINT FK_WarehouseRequests_Value FOREIGN KEY (AttributeValueId)
        REFERENCES AttributeValues (AttributeValueId)
);


-- H. RequestAttributes Table (Captures user selections for each requested item line)
CREATE TABLE IF NOT EXISTS RequestAttributes (
    RequestLineId INT PRIMARY KEY, -- Connects with main checkout request line id
    SKU VARCHAR(50) NOT NULL,
    AttributeTypeId INT NOT NULL,
    AttributeValueId INT NOT NULL,
    SelectedValueTextHe VARCHAR(100) NOT NULL,
    SelectedValueTextEn VARCHAR(100) NOT NULL,
    
    CONSTRAINT FK_RequestAttributes_Type FOREIGN KEY (AttributeTypeId) 
        REFERENCES AttributeTypes (AttributeTypeId),
        
    CONSTRAINT FK_RequestAttributes_Value FOREIGN KEY (AttributeValueId) 
        REFERENCES AttributeValues (AttributeValueId),
    CONSTRAINT FK_RequestAttributes_SKU FOREIGN KEY (SKU)
        REFERENCES WarehouseItems (SKU)
);


-- I. NipukRecords Table (Dispatched and physical delivery tracking)
CREATE TABLE IF NOT EXISTS NipukRecords (
    NipukId VARCHAR(50) PRIMARY KEY,
    DispatchDate DATE NOT NULL,
    DispatchTime VARCHAR(10) NOT NULL,
    OrderNumber VARCHAR(50) NULL,
    RequestDate DATE NULL,
    SKU VARCHAR(50) NULL,
    ItemNameHe VARCHAR(200) NULL,
    ItemNameEn VARCHAR(200) NULL,
    Quantity INT NULL,
    Notes TEXT NULL,
    Remark TEXT NULL,
    AttributeTypeNameHe VARCHAR(100) NULL,
    AttributeValueNameHe VARCHAR(100) NULL,
    AttributeTypeNameEn VARCHAR(100) NULL,
    AttributeValueNameEn VARCHAR(100) NULL,
    WorkerId VARCHAR(100) NOT NULL,
    WorkerName VARCHAR(200) NOT NULL,
    WorkerRole VARCHAR(50) NOT NULL,
    CustomerName VARCHAR(200) NOT NULL,
    CustomerId VARCHAR(100) NULL,
    CustomerPhone VARCHAR(50) NULL,
    CreatedTimestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    LastUpdateTimestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- J. AppUsers Table (System access authorizations and details)
CREATE TABLE IF NOT EXISTS AppUsers (
    UserId VARCHAR(100) PRIMARY KEY,
    TeudatZehut VARCHAR(20) NOT NULL UNIQUE,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    JobTitle VARCHAR(100) NOT NULL,
    Phone VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    PasswordHash VARCHAR(200) NOT NULL,
    Role VARCHAR(50) NOT NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedDate TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    LastLoginDate TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- K. FinancialRateCache (Locally caches Bank of Israel currency logs)
CREATE TABLE IF NOT EXISTS FinancialRateCache (
    CacheId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RateDate DATE NOT NULL,
    CurrencyCode VARCHAR(10) NOT NULL,
    CurrencyNameHe VARCHAR(100) NOT NULL,
    CurrencyNameEn VARCHAR(100) NOT NULL,
    Unit INT NOT NULL DEFAULT 1,
    ExchangeRate DECIMAL(18, 6) NOT NULL,
    LastTrend DECIMAL(12, 6) NOT NULL DEFAULT 0.0,
    TrendPercent DECIMAL(12, 4) NOT NULL DEFAULT 0.0,
    FetchedAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    CONSTRAINT UQ_RateDate_Currency UNIQUE (RateDate, CurrencyCode)
);

-- Index for range date query performance
CREATE INDEX IF NOT EXISTS IX_FinancialRateCache_Date ON FinancialRateCache (RateDate);


-- L. AuditLog Table (Comprehensive changes database ledger)
CREATE TABLE IF NOT EXISTS AuditLog (
    AuditLogId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserId VARCHAR(100) NOT NULL,
    ActionType VARCHAR(50) NOT NULL, -- CREATE / UPDATE / DELETE / ASSIGN
    TableName VARCHAR(100) NOT NULL,
    OldValue JSONB NULL,             -- Saved natively as JSONB instead of NVARCHAR(MAX)
    NewValue JSONB NULL,             -- Saved natively as JSONB instead of NVARCHAR(MAX)
    ActionDate TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    IPAddress VARCHAR(50) NULL
);

-- Index for audit timestamp lookup sorting
CREATE INDEX IF NOT EXISTS IX_AuditLog_ActionDate ON AuditLog (ActionDate DESC);


-- ====================================================================================
-- 2. HIGH-PERFORMANCE PL/pgSQL FUNCTIONS & PROCEDURES 
-- ====================================================================================

-- F1. Dynamic retrieval of attributes and mapped allowed values for a given SKU
-- Note: PostgreSQL uses multiple recordsets returning by declaring individual text/refcursor or returning JSON. 
-- For optimal compatibility with client SDKs (like Supabase JS Client), we provide two dedicated queries returning JSON packets.

CREATE OR REPLACE FUNCTION get_sku_attribute_rules(target_sku VARCHAR)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    result JSONB;
    mapped_types JSONB;
    allowed_vals JSONB;
BEGIN
    -- 1. Gather mapped attribute types with is_mandatory flags
    SELECT COALESCE(jsonb_agg(jsonb_build_object(
        'sku', m.SKU,
        'attribute_type_id', m.AttributeTypeId,
        'type_name_he', t.TypeNameHe,
        'type_name_en', t.TypeNameEn,
        'is_mandatory', m.IsMandatory
    )), '[]'::jsonb)
    INTO mapped_types
    FROM ItemAttributeMapping m
    INNER JOIN AttributeTypes t ON m.AttributeTypeId = t.AttributeTypeId
    WHERE m.SKU = target_sku 
      AND t.IsActive = TRUE 
      AND t.IsDeleted = FALSE;

    -- 2. Gather allowed specific values matching the SKU mapping
    SELECT COALESCE(jsonb_agg(jsonb_build_object(
        'sku', av.SKU,
        'attribute_type_id', v.AttributeTypeId,
        'attribute_value_id', v.AttributeValueId,
        'value_name_he', v.ValueNameHe,
        'value_name_en', v.ValueNameEn
    )), '[]'::jsonb)
    INTO allowed_vals
    FROM ItemAttributeAllowedValues av
    INNER JOIN AttributeValues v ON av.AttributeValueId = v.AttributeValueId
    WHERE av.SKU = target_sku 
      AND v.IsActive = TRUE 
      AND v.IsDeleted = FALSE;

    -- Combine into a single dense structured schema packet
    result := jsonb_build_object(
        'sku', target_sku,
        'mapped_types', mapped_types,
        'allowed_values', allowed_vals
    );
    
    RETURN result;
END;
$$;


-- F2. Save/Update attribute configuration for SKU (equivalent to sp_SaveItemAttributeConfig)
-- Uses JSONB parameters for seamless integration out-of-the-box.
CREATE OR REPLACE PROCEDURE save_item_attribute_config(
    p_sku VARCHAR,
    p_attribute_type_id INT,
    p_is_mandatory BOOLEAN,
    p_allowed_values_json JSONB, -- JSON array of value IDs: e.g. [1, 2, 8]
    p_user_id VARCHAR
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_val_id INT;
BEGIN
    -- Upsert mapping configurations
    INSERT INTO ItemAttributeMapping (SKU, AttributeTypeId, IsMandatory, CreatedBy)
    VALUES (p_sku, p_attribute_type_id, p_is_mandatory, p_user_id)
    ON CONFLICT (SKU, AttributeTypeId) 
    DO UPDATE SET 
        IsMandatory = p_is_mandatory;

    -- Clean up previous values mapped to this type-item relationship 
    DELETE FROM ItemAttributeAllowedValues
    WHERE SKU = p_sku AND AttributeTypeId = p_attribute_type_id;

    -- Re-insert white-listed subset from the parsed array elements
    INSERT INTO ItemAttributeAllowedValues (SKU, AttributeTypeId, AttributeValueId)
    SELECT p_sku, p_attribute_type_id, (val::text)::INT
    FROM jsonb_array_elements_text(p_allowed_values_json) AS val;

    -- Append audit ledger trail update log
    INSERT INTO AuditLog (UserId, ActionType, TableName, OldValue, NewValue)
    VALUES (
        p_user_id, 
        'ASSIGN', 
        'ItemAttributeConfig', 
        jsonb_build_object('sku', p_sku, 'attribute_type_id', p_attribute_type_id),
        jsonb_build_object('is_mandatory', p_is_mandatory, 'allowed_values', p_allowed_values_json)
    );
END;
$$;


-- F3. Daily Currency lookup procedure matching the daily target date
CREATE OR REPLACE FUNCTION get_financial_rates_by_date(target_date DATE)
RETURNS TABLE (
    rate_date DATE,
    currency_code VARCHAR,
    currency_name_he VARCHAR,
    currency_name_en VARCHAR,
    unit INT,
    exchange_rate DECIMAL,
    last_trend DECIMAL,
    trend_percent DECIMAL,
    fetched_at TIMESTAMPTZ
) 
LANGUAGE SQL
AS $$
    SELECT 
        RateDate,
        CurrencyCode,
        CurrencyNameHe,
        CurrencyNameEn,
        Unit,
        ExchangeRate,
        LastTrend,
        TrendPercent,
        FetchedAt
    FROM 
        FinancialRateCache
    WHERE 
        RateDate = target_date
    ORDER BY 
        CASE CurrencyCode 
            WHEN 'USD' THEN 1 
            WHEN 'EUR' THEN 2 
            WHEN 'GBP' THEN 3 
            ELSE 4 
        END, 
        CurrencyCode ASC;
$$;


-- F4. Atomic UPSERT/MERGE currency rates parser (protects against high concurrency lockouts)
CREATE OR REPLACE FUNCTION upsert_financial_rate(
    p_rate_date DATE,
    p_currency_code VARCHAR,
    p_currency_name_he VARCHAR,
    p_currency_name_en VARCHAR,
    p_unit INT,
    p_exchange_rate DECIMAL,
    p_last_trend DECIMAL,
    p_trend_percent DECIMAL
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO FinancialRateCache (
        RateDate,
        CurrencyCode,
        CurrencyNameHe,
        CurrencyNameEn,
        Unit,
        ExchangeRate,
        LastTrend,
        TrendPercent,
        FetchedAt
    )
    VALUES (
        p_rate_date,
        p_currency_code,
        p_currency_name_he,
        p_currency_name_en,
        p_unit,
        p_exchange_rate,
        p_last_trend,
        p_trend_percent,
        NOW()
    )
    ON CONFLICT (RateDate, CurrencyCode)
    DO UPDATE SET 
        CurrencyNameHe = p_currency_name_he,
        CurrencyNameEn = p_currency_name_en,
        Unit = p_unit,
        ExchangeRate = p_exchange_rate,
        LastTrend = p_last_trend,
        TrendPercent = p_trend_percent,
        FetchedAt = NOW();
END;
$$;


-- ====================================================================================
-- 3. OPTIONAL SUPABASE ROW LEVEL SECURITY (RLS) POLICIES
-- ====================================================================================

-- Note: In Supabase, Row Level Security is enabled by default to secure tables against anonymous writes.
-- These lines configure public read access and authenticated editor privileges for compliance.

-- Alter tables to enable Security
ALTER TABLE AttributeTypes ENABLE ROW LEVEL SECURITY;
ALTER TABLE AttributeValues ENABLE ROW LEVEL SECURITY;
ALTER TABLE WarehouseItems ENABLE ROW LEVEL SECURITY;
ALTER TABLE ItemPictureUrls ENABLE ROW LEVEL SECURITY;
ALTER TABLE ItemAttributeMapping ENABLE ROW LEVEL SECURITY;
ALTER TABLE ItemAttributeAllowedValues ENABLE ROW LEVEL SECURITY;
ALTER TABLE WarehouseRequests ENABLE ROW LEVEL SECURITY;
ALTER TABLE RequestAttributes ENABLE ROW LEVEL SECURITY;
ALTER TABLE NipukRecords ENABLE ROW LEVEL SECURITY;
ALTER TABLE AppUsers ENABLE ROW LEVEL SECURITY;
ALTER TABLE FinancialRateCache ENABLE ROW LEVEL SECURITY;
ALTER TABLE AuditLog ENABLE ROW LEVEL SECURITY;

-- 1. Create Policies for Read accessibility (Public or authenticated)
CREATE POLICY "Allow public read of AttributeTypes" ON AttributeTypes FOR SELECT TO public USING (NOT IsDeleted);
CREATE POLICY "Allow public read of AttributeValues" ON AttributeValues FOR SELECT TO public USING (NOT IsDeleted);
CREATE POLICY "Allow public read of WarehouseItems" ON WarehouseItems FOR SELECT TO public USING (TRUE);
CREATE POLICY "Allow public read of ItemPictureUrls" ON ItemPictureUrls FOR SELECT TO public USING (IsActive = TRUE);
CREATE POLICY "Allow public read of Mapping" ON ItemAttributeMapping FOR SELECT TO public USING (TRUE);
CREATE POLICY "Allow public read of AllowedValues" ON ItemAttributeAllowedValues FOR SELECT TO public USING (TRUE);
CREATE POLICY "Allow public read of WarehouseRequests" ON WarehouseRequests FOR SELECT TO public USING (TRUE);
CREATE POLICY "Allow public read of RequestAttributes" ON RequestAttributes FOR SELECT TO public USING (TRUE);
CREATE POLICY "Allow public read of NipukRecords" ON NipukRecords FOR SELECT TO public USING (TRUE);
CREATE POLICY "Allow public read of AppUsers" ON AppUsers FOR SELECT TO public USING (IsActive = TRUE);
CREATE POLICY "Allow public read of ExchangeRates" ON FinancialRateCache FOR SELECT TO public USING (TRUE);

-- 2. Create Policies for writing permission (Authenticated staff/architect editors only)
-- Note: 'auth.role() = ''authenticated''' checks if the user is logged into Supabase Auth.
CREATE POLICY "Allow authenticated editors write of AttributeTypes" ON AttributeTypes FOR ALL TO authenticated USING (TRUE);
CREATE POLICY "Allow authenticated editors write of AttributeValues" ON AttributeValues FOR ALL TO authenticated USING (TRUE);
CREATE POLICY "Allow authenticated editors write of WarehouseItems" ON WarehouseItems FOR ALL TO authenticated USING (TRUE);
CREATE POLICY "Allow authenticated editors write of ItemPictureUrls" ON ItemPictureUrls FOR ALL TO authenticated USING (TRUE);
CREATE POLICY "Allow authenticated editors write of Mapping" ON ItemAttributeMapping FOR ALL TO authenticated USING (TRUE);
CREATE POLICY "Allow authenticated editors write of AllowedValues" ON ItemAttributeAllowedValues FOR ALL TO authenticated USING (TRUE);
CREATE POLICY "Allow authenticated editors write of WarehouseRequests" ON WarehouseRequests FOR ALL TO authenticated USING (TRUE);
CREATE POLICY "Allow authenticated editors write of RequestAttributes" ON RequestAttributes FOR ALL TO authenticated USING (TRUE);
CREATE POLICY "Allow authenticated editors write of NipukRecords" ON NipukRecords FOR ALL TO authenticated USING (TRUE);
CREATE POLICY "Allow authenticated editors write of AppUsers" ON AppUsers FOR ALL TO authenticated USING (TRUE);
CREATE POLICY "Allow authenticated editors write of ExchangeRates" ON FinancialRateCache FOR ALL TO authenticated USING (TRUE);
CREATE POLICY "Allow authenticated editors write of AuditLog" ON AuditLog FOR ALL TO authenticated USING (TRUE);

-- Clear rate limits/test caches
TRUNCATE TABLE FinancialRateCache CASCADE;

-- ====================================================================================
-- SETUP COMPLETED SUCCESSFULLY!
-- Paste this script directly inside Supabase SQL Editor (https://supabase.com)
-- and configure your clients to query table schemas securely. 
-- ====================================================================================
`
  },
  {
    filename: "Schema_and_Procedures.sql",
    language: "sql",
    titleHe: "סכמת מסד נתונים ופרוצדורות מוגדרות",
    titleEn: "Database Schema & Stored Procedures",
    descriptionHe: "(שימו לב: עבור שרת SQL Server בלבד! לא להריץ ב-Supabase) סקריפטים ליצירת טבלאות מנורמלות, מפתח זר, אינדקסים ותמיכה במחיקה רכה יחד עם פרוצדורות שמורות אופטימליות.",
    descriptionEn: "(Warning: For SQL Server ONLY! Do not run in Supabase) Highly optimized SQL server MS-SQL scripts creating the normalized schema schema, indices, soft delete flags, and stored procedures for dynamic binding.",
    code: `-- =====================================================================
-- SYSTEM: Agricultural Research Center Warehouse Request Management System
-- MODULE: Item Attributes Management (מערכת מאפייני פריטים)
-- DESIGNED BY: Senior Enterprise Architect
-- COMPATIBILITY: SQL Server 2012+
-- =====================================================================

USE [WarehouseRequestsDB];
GO

-- 1. ATTRIBUTE TYPES TABLE (Size, Color, Model...)
CREATE TABLE [dbo].[AttributeTypes] (
    [AttributeTypeId] INT IDENTITY(1,1) NOT NULL,
    [TypeNameEn] NVARCHAR(100) NOT NULL,
    [TypeNameHe] NVARCHAR(100) NOT NULL,
    [IsActive] BIT NOT NULL DEFAULT 1,
    [IsDeleted] BIT NOT NULL DEFAULT 0,
    [CreatedDate] DATETIME NOT NULL DEFAULT GETDATE(),
    [CreatedBy] NVARCHAR(100) NOT NULL,
    CONSTRAINT [PK_AttributeTypes] PRIMARY KEY CLUSTERED ([AttributeTypeId] ASC),
    CONSTRAINT [UQ_AttributeTypeNameEn] UNIQUE ([TypeNameEn]),
    CONSTRAINT [UQ_AttributeTypeNameHe] UNIQUE ([TypeNameHe])
);
CREATE NONCLUSTERED INDEX [IX_AttributeTypes_Active_Deleted] 
ON [dbo].[AttributeTypes] ([IsActive], [IsDeleted]) 
INCLUDE ([TypeNameHe], [TypeNameEn]);
GO

-- 2. ATTRIBUTE VALUES TABLE (S, M, L, Red, Blue...)
CREATE TABLE [dbo].[AttributeValues] (
    [AttributeValueId] INT IDENTITY(1,1) NOT NULL,
    [AttributeTypeId] INT NOT NULL,
    [ValueNameEn] NVARCHAR(100) NOT NULL,
    [ValueNameHe] NVARCHAR(100) NOT NULL,
    [IsActive] BIT NOT NULL DEFAULT 1,
    [IsDeleted] BIT NOT NULL DEFAULT 0,
    [CreatedDate] DATETIME NOT NULL DEFAULT GETDATE(),
    [CreatedBy] NVARCHAR(100) NOT NULL,
    CONSTRAINT [PK_AttributeValues] PRIMARY KEY CLUSTERED ([AttributeValueId] ASC),
    CONSTRAINT [FK_AttributeValues_AttributeTypes] FOREIGN KEY ([AttributeTypeId]) 
        REFERENCES [dbo].[AttributeTypes] ([AttributeTypeId]) ON DELETE CASCADE,
    CONSTRAINT [UQ_AttributeValue_Type_Name] UNIQUE ([AttributeTypeId], [ValueNameHe])
);
CREATE NONCLUSTERED INDEX [IX_AttributeValues_TypeId_Active] 
ON [dbo].[AttributeValues] ([AttributeTypeId], [IsActive], [IsDeleted])
INCLUDE ([ValueNameHe], [ValueNameEn]);
GO

-- 3. ITEM METADATA ATTRIBS MAPPING TABLE (Maps Attribute Type to SKU)
CREATE TABLE [dbo].[ItemAttributeMapping] (
    [SKU] NVARCHAR(50) NOT NULL, -- Logical link to existing static items imported from Excel
    [AttributeTypeId] INT NOT NULL,
    [IsMandatory] BIT NOT NULL DEFAULT 0,
    [CreatedDate] DATETIME NOT NULL DEFAULT GETDATE(),
    [CreatedBy] NVARCHAR(100) NOT NULL,
    CONSTRAINT [PK_ItemAttributeMapping] PRIMARY KEY CLUSTERED ([SKU] ASC, [AttributeTypeId] ASC),
    CONSTRAINT [FK_ItemAttributeMapping_AttributeTypes] FOREIGN KEY ([AttributeTypeId])
        REFERENCES [dbo].[AttributeTypes] ([AttributeTypeId])
);
GO

-- 4. ALLOWED ATTRIBUTE VALUES PER ITEM Table (Selective values)
CREATE TABLE [dbo].[ItemAttributeAllowedValues] (
    [SKU] NVARCHAR(50) NOT NULL,
    [AttributeTypeId] INT NOT NULL,
    [AttributeValueId] INT NOT NULL,
    CONSTRAINT [PK_ItemAttributeAllowedValues] PRIMARY KEY CLUSTERED ([SKU], [AttributeTypeId], [AttributeValueId]),
    CONSTRAINT [FK_ItemAttributeAllowedValues_Mapping] FOREIGN KEY ([SKU], [AttributeTypeId])
        REFERENCES [dbo].[ItemAttributeMapping] ([SKU], [AttributeTypeId]) ON DELETE CASCADE,
    CONSTRAINT [FK_ItemAttributeAllowedValues_Value] FOREIGN KEY ([AttributeValueId])
        REFERENCES [dbo].[AttributeValues] ([AttributeValueId])
);
GO

-- 5. REQUEST DETAILS EXTENSION TABLE (Selected attribute per line request)
CREATE TABLE [dbo].[RequestAttributes] (
    [RequestLineId] INT NOT NULL, -- Link to existing primary Requests table
    [SKU] NVARCHAR(50) NOT NULL,
    [AttributeTypeId] INT NOT NULL,
    [AttributeValueId] INT NOT NULL,
    [SelectedValueTextHe] NVARCHAR(100) NOT NULL,
    [SelectedValueTextEn] NVARCHAR(100) NOT NULL,
    CONSTRAINT [PK_RequestAttributes] PRIMARY KEY CLUSTERED ([RequestLineId] ASC),
    CONSTRAINT [FK_RequestAttributes_Type] FOREIGN KEY ([AttributeTypeId]) 
        REFERENCES [dbo].[AttributeTypes] ([AttributeTypeId]),
    CONSTRAINT [FK_RequestAttributes_Value] FOREIGN KEY ([AttributeValueId]) 
        REFERENCES [dbo].[AttributeValues] ([AttributeValueId])
);
GO

-- 6. COMPREHENSIVE AUDIT LOG TABLE (Compliance & History tracking)
CREATE TABLE [dbo].[AuditLog] (
    [AuditLogId] BIGINT IDENTITY(1,1) NOT NULL,
    [UserId] NVARCHAR(100) NOT NULL,
    [ActionType] NVARCHAR(50) NOT NULL, -- CREATE / UPDATE / DELETE / ASSIGN
    [TableName] NVARCHAR(100) NOT NULL,
    [OldValue] NVARCHAR(MAX) NULL,
    [NewValue] NVARCHAR(MAX) NULL,
    [ActionDate] DATETIME NOT NULL DEFAULT GETDATE(),
    [IPAddress] NVARCHAR(50) NULL,
    CONSTRAINT [PK_AuditLog] PRIMARY KEY CLUSTERED ([AuditLogId] DESC)
);
CREATE NONCLUSTERED INDEX [IX_AuditLog_ActionDate] ON [dbo].[AuditLog] ([ActionDate] DESC);
GO


-- =====================================================================
-- STORED PROCEDURES FOR HIGH-PERFORMANCE DATA RETRIEVAL
-- =====================================================================

-- P1. Dynamic retrieval of items attribute configs during requests
CREATE PROCEDURE [dbo].[sp_GetItemAttributesForSelection]
    @SKU NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    -- Retrieve mapped attribute type list and mandatory settings for item
    SELECT 
        m.[SKU],
        m.[AttributeTypeId],
        t.[TypeNameHe] AS [AttributeTypeNameHe],
        t.[TypeNameEn] AS [AttributeTypeNameEn],
        m.[IsMandatory]
    FROM [dbo].[ItemAttributeMapping] m
    INNER JOIN [dbo].[AttributeTypes] t ON m.[AttributeTypeId] = t.[AttributeTypeId]
    WHERE m.[SKU] = @SKU 
      AND t.[IsActive] = 1 
      AND t.[IsDeleted] = 0;

    -- Retrieve specifically allowed values for matching SKU
    SELECT 
        av.[SKU],
        v.[AttributeTypeId],
        v.[AttributeValueId],
        v.[ValueNameHe] AS [AttributeValueNameHe],
        v.[ValueNameEn] AS [AttributeValueNameEn]
    FROM [dbo].[ItemAttributeAllowedValues] av
    INNER JOIN [dbo].[AttributeValues] v ON av.[AttributeValueId] = v.[AttributeValueId]
    WHERE av.[SKU] = @SKU 
      AND v.[IsActive] = 1 
      AND v.[IsDeleted] = 0;
END
GO

-- P2. Save/Update attribute configuration for a specific SKU (Transactional)
CREATE PROCEDURE [dbo].[sp_SaveItemAttributeConfig]
    @SKU NVARCHAR(50),
    @AttributeTypeId INT,
    @IsMandatory BIT,
    @AllowedValuesJson NVARCHAR(MAX), -- JSON array of selected Value IDs
    @UserId NVARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    BEGIN TRANSACTION;
    BEGIN TRY
        -- Check if Mapping exists
        IF EXISTS (SELECT 1 FROM [dbo].[ItemAttributeMapping] WHERE [SKU] = @SKU AND [AttributeTypeId] = @AttributeTypeId)
        BEGIN
            UPDATE [dbo].[ItemAttributeMapping]
            SET [IsMandatory] = @IsMandatory
            WHERE [SKU] = @SKU AND [AttributeTypeId] = @AttributeTypeId;
        END
        ELSE
        BEGIN
            INSERT INTO [dbo].[ItemAttributeMapping] ([SKU], [AttributeTypeId], [IsMandatory], [CreatedBy])
            VALUES (@SKU, @AttributeTypeId, @IsMandatory, @UserId);
        END

        -- Clean up previous allowed list values for this SKU type
        DELETE FROM [dbo].[ItemAttributeAllowedValues]
        WHERE [SKU] = @SKU AND [AttributeTypeId] = @AttributeTypeId;

        -- Extract and insert allowed lists
        INSERT INTO [dbo].[ItemAttributeAllowedValues] ([SKU], [AttributeTypeId], [AttributeValueId])
        SELECT @SKU, @AttributeTypeId, CAST([value] AS INT)
        FROM OPENJSON(@AllowedValuesJson);

        -- Insert audit trail record
        INSERT INTO [dbo].[AuditLog] ([UserId], [ActionType], [TableName], [OldValue], [NewValue])
        VALUES (@UserId, 'ASSIGN', 'ItemAttributeConfig', 
                'SKU: ' + @SKU + ', TypeId: ' + CAST(@AttributeTypeId AS VARCHAR),
                'Mandatory: ' + CAST(@IsMandatory AS VARCHAR) + ', ValuesJSON: ' + @AllowedValuesJson);

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END
GO
`
  },
  {
    filename: "ItemAttributes.aspx",
    language: "xml",
    titleHe: "מסך ניהול מאפיינים עיקרי - ItemAttributes.aspx",
    titleEn: "WebForm Markup - ItemAttributes.aspx",
    descriptionHe: "קוד תצוגה מבוסס ASP.NET Web Forms עם תמיכה מלאה ב-RTL (עברית לחלוטין), GridViews, טפסים דינמיים, כפתורי נעילה ואינדיקטורים.",
    descriptionEn: "Visual ASPX layout with high accessibility and full RTL compatibility utilizing Web Forms server components and clean CSS formatting.",
    code: `<%@ Page Title="ניהול מאפייני פריטים - מכון וולקני" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ItemAttributes.aspx.cs" Inherits="WarehouseRequests.Admin.ItemAttributes" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <!-- RTL CSS Grid Container -->
    <div class="enterprise-container" style="direction: rtl; text-align: right; padding: 20px;">
        <div class="row mb-4" style="border-bottom: 2px solid #005691; padding-bottom: 15px;">
            <div class="col-md-8">
                <h1 style="color: #005691; font-size: 26px; font-weight: 500;">
                    <i class="fa fa-tags"></i> ניהול קטגוריות ומאפייני פריטים
                </h1>
                <p style="color: #666; font-size: 14px; margin-top: 5px;">
                    כלי מנהל מחסן לקביעת תיוגים, צבעים ומידות הנדרשים לרישום בקשות ניפוק חקלאיות מול ERP מרכבה.
                </p>
            </div>
            <div class="col-md-4 text-left font-weight-bold">
                <span class="badge badge-primary p-2" style="font-size: 13px;">
                    <i class="fa fa-user-shield"></i> מורשה: מנהל מחסן (Warehouse Manager)
                </span>
            </div>
        </div>

        <!-- Success/Error Alert Panel -->
        <asp:Panel ID="pnlNotification" runat="server" Visible="false" CssClass="alert alert-dismissible" role="alert">
            <asp:Label ID="lblNotificationMessage" runat="server"></asp:Label>
        </asp:Panel>

        <div class="row">
            <!-- Left Side: Attribute Types Form & Grid -->
            <div class="col-md-6">
                <div class="card card-enterprise">
                    <div class="card-header font-weight-bold bg-light">סוגי מאפיינים ראשיים</div>
                    <div class="card-body">
                        
                        <!-- Create Row -->
                        <div class="well p-3 mb-3 bg-light border">
                            <h5 class="text-primary font-size-14" style="margin-top:0;">סוג מאפיין חדש:</h5>
                            <div class="form-row align-items-center">
                                <div class="col-sm-5">
                                    <asp:TextBox ID="txtTypeNameHe" runat="server" CssClass="form-control mb-2" placeholder="עברית (למשל: מידה)" Required="true"></asp:TextBox>
                                </div>
                                <div class="col-sm-5">
                                    <asp:TextBox ID="txtTypeNameEn" runat="server" CssClass="form-control mb-2" placeholder="English (e.g. Size)" Required="true"></asp:TextBox>
                                </div>
                                <div class="col-sm-2 text-left">
                                    <asp:Button ID="btnSaveType" runat="server" Text="שמור" CssClass="btn btn-primary mb-2 btn-block" OnClick="btnSaveType_Click" />
                                </div>
                            </div>
                        </div>

                        <!-- Grid -->
                        <asp:GridView ID="gvTypes" runat="server" AutoGenerateColumns="False" DataKeyNames="AttributeTypeId"
                            CssClass="table table-bordered table-striped" OnSelectedIndexChanged="gvTypes_SelectedIndexChanged"
                            OnRowDeleting="gvTypes_RowDeleting">
                            <Columns>
                                <asp:BoundField DataField="AttributeTypeId" HeaderText="מזהה" ReadOnly="True" ItemStyle-Width="10%" />
                                <asp:BoundField DataField="TypeNameHe" HeaderText="שם בעברית" />
                                <asp:BoundField DataField="TypeNameEn" HeaderText="שם באנגלית" />
                                <asp:TemplateField HeaderText="סטטוס">
                                    <ItemTemplate>
                                        <asp:LinkButton ID="lnkToggleActive" runat="server" OnCommand="lnkToggleActive_Command" CommandArgument='<%# Eval("AttributeTypeId") %>'
                                            CssClass='<%# (bool)Eval("IsActive") ? "badge badge-success" : "badge badge-secondary" %>'>
                                            <%# (bool)Eval("IsActive") ? "פעיל" : "לא פעיל" %>
                                        </asp:LinkButton>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:CommandField ShowSelectButton="True" SelectText="ערכים &raquo;" ControlStyle-CssClass="btn btn-sm btn-info text-white" />
                                <asp:TemplateField>
                                    <ItemTemplate>
                                        <asp:LinkButton ID="lnkDeleteType" runat="server" CommandName="Delete" Text="מחק"
                                            OnClientClick="return confirm('האם למחוק סוג מאפיין זה וכל הערכים שלו?');"
                                            CssClass="btn btn-sm btn-danger text-white"></asp:LinkButton>
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Columns>
                            <SelectedRowStyle BackColor="#EAF4FC" Font-Bold="True" />
                        </asp:GridView>
                    </div>
                </div>
            </div>

            <!-- Right Side: Values Form & Grid per Type select -->
            <div class="col-md-6">
                <asp:Panel ID="pnlValues" runat="server" Enabled="false" style="opacity: 0.6;">
                    <div class="card card-enterprise">
                        <div class="card-header font-weight-bold bg-light">
                            ערכים עבור: <asp:Label ID="lblSelectedTypeName" runat="server" Text="[בחר סוג מאפיין]"></asp:Label>
                        </div>
                        <div class="card-body">
                            
                            <!-- Save value form -->
                            <div class="well p-3 mb-3 bg-light border">
                                <h5 class="text-warning font-size-14" style="margin-top:0;">ערך מאפיין חדש:</h5>
                                <div class="form-row align-items-center">
                                    <div class="col-sm-5">
                                        <asp:TextBox ID="txtValueHe" runat="server" CssClass="form-control mb-2" placeholder="למשל: גדול" Required="true"></asp:TextBox>
                                    </div>
                                    <div class="col-sm-5">
                                        <asp:TextBox ID="txtValueEn" runat="server" CssClass="form-control mb-2" placeholder="e.g. Large" Required="true"></asp:TextBox>
                                    </div>
                                    <div class="col-sm-2">
                                        <asp:Button ID="btnSaveValue" runat="server" Text="הוסף" CssClass="btn btn-warning mb-2 btn-block text-dark font-weight-bold" OnClick="btnSaveValue_Click" />
                                    </div>
                                </div>
                            </div>

                            <asp:GridView ID="gvValues" runat="server" AutoGenerateColumns="False" DataKeyNames="AttributeValueId"
                                CssClass="table table-bordered table-striped" OnRowDeleting="gvValues_RowDeleting">
                                <Columns>
                                    <asp:BoundField DataField="AttributeValueId" HeaderText="ID" ItemStyle-Width="15%" />
                                    <asp:BoundField DataField="ValueNameHe" HeaderText="ערך בעברית" />
                                    <asp:BoundField DataField="ValueNameEn" HeaderText="ערך באנגלית" />
                                    <asp:TemplateField HeaderText="סטטוס">
                                        <ItemTemplate>
                                            <asp:LinkButton ID="lnkToggleValueActive" runat="server" OnCommand="lnkToggleValueActive_Command" CommandArgument='<%# Eval("AttributeValueId") %>'
                                                CssClass='<%# (bool)Eval("IsActive") ? "badge badge-success" : "badge badge-secondary" %>'>
                                                <%# (bool)Eval("IsActive") ? "פעיל" : "לא פעיל" %>
                                            </asp:LinkButton>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField>
                                        <ItemTemplate>
                                            <asp:LinkButton ID="lnkDeleteValue" runat="server" CommandName="Delete" Text="הסר"
                                                OnClientClick="return confirm('האם להסיר ערך זה?');"
                                                CssClass="btn btn-sm btn-outline-danger"></asp:LinkButton>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                </Columns>
                            </asp:GridView>
                        </div>
                    </div>
                </asp:Panel>
            </div>
        </div>
    </div>
</asp:Content>
`
  },
  {
    filename: "ItemAttributes.aspx.cs",
    language: "charp",
    titleHe: "קוד ה-Code-Behind בארכיטקטורת enterprise - ItemAttributes.aspx.cs",
    titleEn: "Code-Behind - ItemAttributes.aspx.cs",
    descriptionHe: "קובץ קוד השרת (C# .aspx.cs) הכולל בדיקת הרשאות מחסנאי, אינטגרציה עם שכבת ה-BLL, תהליכים מנוהלי טרנזקציה וכתיבת לוג שינויים (Audit) מפורט למסד הנתונים.",
    descriptionEn: "Server-side C# implementation protecting administration commands by user group authorization, structured error handling, and audit tracing.",
    code: `using System;
using System.Data;
using System.Web.UI;
using System.Web.UI.WebControls;
using WarehouseRequests.BLL;
using WarehouseRequests.Models;

namespace WarehouseRequests.Admin
{
    public partial class ItemAttributes : System.Web.UI.Page
    {
        private readonly WarehouseAttributeBLL _attribBll = new WarehouseAttributeBLL();
        private readonly AuditService _auditService = new AuditService();

        protected void Page_Load(object sender, EventArgs e)
        {
            // 1. Double-Layer Security Validation: Check if user is a Warehouse Manager
            if (!User.Identity.IsAuthenticated || !User.IsInRole("WarehouseManagers"))
            {
                // Log unauthorized attempts and redirect
                _auditService.LogAction("UNKNOWN", "ACCESS_DENIED", "AttributeTypes", "", "Unauthorized user tried to load ItemAttributes.aspx");
                Response.Redirect("~/Unauthorized.aspx");
                return;
            }

            if (!IsPostBack)
            {
                BindTypesGrid();
            }
        }

        private void BindTypesGrid()
        {
            try
            {
                DataTable dt = _attribBll.GetAllAttributeTypes(includeDeleted: false);
                gvTypes.DataSource = dt;
                gvTypes.DataBind();
            }
            catch (Exception ex)
            {
                ShowNotification("שגיאה בטעינת סוגי המאפיינים: " + ex.Message, isSuccess: false);
            }
        }

        private void BindValuesGrid(int attributeTypeId)
        {
            try
            {
                DataTable dt = _attribBll.GetValuesByTypeId(attributeTypeId, includeDeleted: false);
                gvValues.DataSource = dt;
                gvValues.DataBind();
            }
            catch (Exception ex)
            {
                ShowNotification("שגיאה בטעינת ערכי המאפיין: " + ex.Message, isSuccess: false);
            }
        }

        protected void btnSaveType_Click(object sender, EventArgs e)
        {
            string nameHe = txtTypeNameHe.Text.Trim();
            string nameEn = txtTypeNameEn.Text.Trim();
            string userId = User.Identity.Name;

            if (string.IsNullOrEmpty(nameHe) || string.IsNullOrEmpty(nameEn))
            {
                ShowNotification("אנא הזמן שם תקני בעברית ובאנגלית.", isSuccess: false);
                return;
            }

            try
            {
                // Integrity check: Unique Name Validation
                if (_attribBll.IsTypeNameExists(nameHe, nameEn))
                {
                    ShowNotification("שגיאה: שם המאפיין כבר קיים במערכת.", isSuccess: false);
                    return;
                }

                bool result = _attribBll.InsertAttributeType(nameHe, nameEn, userId);
                if (result)
                {
                    _auditService.LogAction(userId, "CREATE", "AttributeTypes", null, $"Created Type '{nameHe}' / '{nameEn}'");
                    ShowNotification("סוג המאפיין נשמר בהצלחה.", isSuccess: true);
                    txtTypeNameHe.Text = "";
                    txtTypeNameEn.Text = "";
                    BindTypesGrid();
                }
            }
            catch (Exception ex)
            {
                ShowNotification("שגיאה בשמירת סוג המאפיין: " + ex.Message, isSuccess: false);
            }
        }

        protected void gvTypes_SelectedIndexChanged(object sender, EventArgs e)
        {
            int selectedTypeId = Convert.ToInt32(gvTypes.SelectedValue);
            string chosenHeName = gvTypes.SelectedRow.Cells[1].Text;

            ViewState["SelectedAttributeTypeId"] = selectedTypeId;
            lblSelectedTypeName.Text = Server.HtmlEncode(chosenHeName);
            
            // Enable the value subform panel
            pnlValues.Enabled = true;
            pnlValues.Style["opacity"] = "1.0";

            BindValuesGrid(selectedTypeId);
        }

        protected void btnSaveValue_Click(object sender, EventArgs e)
        {
            if (ViewState["SelectedAttributeTypeId"] == null) return;
            int typeId = (int)ViewState["SelectedAttributeTypeId"];
            string valHe = txtValueHe.Text.Trim();
            string valEn = txtValueEn.Text.Trim();
            string userId = User.Identity.Name;

            try
            {
                // Unique check within active values of this type
                if (_attribBll.IsValueExists(typeId, valHe, valEn))
                {
                    ShowNotification("שגיאה: ערך מאפיין זה כבר מוגדר בקטגוריה זו.", isSuccess: false);
                    return;
                }

                bool result = _attribBll.InsertAttributeValue(typeId, valHe, valEn, userId);
                if (result)
                {
                    _auditService.LogAction(userId, "CREATE", "AttributeValues", null, $"Added value '{valHe}' to Type ID: {typeId}");
                    ShowNotification("הערך נוסף בהצלחה לקטגוריה.", isSuccess: true);
                    txtValueHe.Text = "";
                    txtValueEn.Text = "";
                    BindValuesGrid(typeId);
                }
            }
            catch (Exception ex)
            {
                ShowNotification("שגיאה בהוספת הערך: " + ex.Message, isSuccess: false);
            }
        }

        protected void lnkToggleActive_Command(object sender, CommandEventArgs e)
        {
            int typeId = Convert.ToInt32(e.CommandArgument);
            string userId = User.Identity.Name;
            try
            {
                _attribBll.ToggleTypeActiveStatus(typeId, userId);
                _auditService.LogAction(userId, "UPDATE", "AttributeTypes", $"TypeID: {typeId}", "Toggled Active status");
                BindTypesGrid();
            }
            catch (Exception ex)
            {
                ShowNotification("שגיאה בשינוי סטטוס המאפיין: " + ex.Message, isSuccess: false);
            }
        }

        protected void lnkToggleValueActive_Command(object sender, CommandEventArgs e)
        {
            int valId = Convert.ToInt32(e.CommandArgument);
            string userId = User.Identity.Name;
            try
            {
                _attribBll.ToggleValueActiveStatus(valId, userId);
                _auditService.LogAction(userId, "UPDATE", "AttributeValues", $"ValueID: {valId}", "Toggled value Active status");
                if (ViewState["SelectedAttributeTypeId"] != null)
                {
                    BindValuesGrid((int)ViewState["SelectedAttributeTypeId"]);
                }
            }
            catch (Exception ex)
            {
                ShowNotification("שגיאה בשינוי סטטוס הערך: " + ex.Message, isSuccess: false);
            }
        }

        protected void gvTypes_RowDeleting(object sender, GridViewDeleteEventArgs e)
        {
            int typeId = Convert.ToInt32(gvTypes.DataKeys[e.RowIndex].Value);
            string userId = User.Identity.Name;
            try
            {
                _attribBll.SoftDeleteAttributeType(typeId, userId);
                _auditService.LogAction(userId, "DELETE", "AttributeTypes", $"TypeID: {typeId}", "Soft deleted attribute type and its dependencies");
                ShowNotification("סוג המאפיין נמחק בהצלחה (מחיקה רכה).", isSuccess: true);
                
                // Clear state selection if we deleted the selected type
                if (ViewState["SelectedAttributeTypeId"] != null && (int)ViewState["SelectedAttributeTypeId"] == typeId)
                {
                    ViewState["SelectedAttributeTypeId"] = null;
                    lblSelectedTypeName.Text = "[בחר סוג מאפיין]";
                    pnlValues.Enabled = false;
                    pnlValues.Style["opacity"] = "0.6";
                    gvValues.DataSource = null;
                    gvValues.DataBind();
                }

                BindTypesGrid();
            }
            catch (Exception ex)
            {
                ShowNotification("שגיאה במחיקת המאפיין: " + ex.Message, isSuccess: false);
            }
        }

        protected void gvValues_RowDeleting(object sender, GridViewDeleteEventArgs e)
        {
            int valId = Convert.ToInt32(gvValues.DataKeys[e.RowIndex].Value);
            string userId = User.Identity.Name;
            try
            {
                _attribBll.SoftDeleteAttributeValue(valId, userId);
                _auditService.LogAction(userId, "DELETE", "AttributeValues", $"ValueID: {valId}", "Soft deleted attribute value");
                ShowNotification("הערך נמחק בהצלחה (מחיקה רכה).", isSuccess: true);
                if (ViewState["SelectedAttributeTypeId"] != null)
                {
                    BindValuesGrid((int)ViewState["SelectedAttributeTypeId"]);
                }
            }
            catch (Exception ex)
            {
                ShowNotification("שגיאה בהסרת הערך: " + ex.Message, isSuccess: false);
            }
        }

        private void ShowNotification(string message, bool isSuccess)
        {
            pnlNotification.Visible = true;
            pnlNotification.CssClass = isSuccess ? "alert alert-success" : "alert alert-danger";
            lblNotificationMessage.Text = Server.HtmlEncode(message);
        }
    }
}
`
  },
  {
    filename: "Dynamic_Selector.js",
    language: "javascript",
    titleHe: "קוד JS אסינכרוני לטעינת מאפיינים - Dynamic_Selector.js",
    titleEn: "Dynamic Selector Script - Dynamic_Selector.js",
    descriptionHe: "סקריפט צד לקוח המבצע קריאת AJAX אסינכרונית ל-WebMethod שיתופי בשרת בעת בחירת מק\"ט, מאחזר את המאפיינים המותרים, ומחולל DropDown דינמי בעברית/אנגלית.",
    descriptionEn: "Highly efficient jQuery Client-side component fetching applicable values on demand and applying local Hebrew/English localization dynamically.",
    code: `/**
 * Agricultural Research Center Warehouse Request Dynamic Attribute Selector Helper Script
 * Supports RTL formatting, dynamic AJAX binding, and mandatory client-side validations.
 */

$(document).ready(function () {
    // Watch for dynamic SKU item selection dropdown or searching changes
    $("#ddlWarehouseItems, #txtItemSkuSearch").on("change input", function () {
        var selectedSku = $(this).val();
        if (selectedSku) {
            fetchAndRenderDynamicAttributes(selectedSku);
        } else {
            clearAttributePlaceholders();
        }
    });
});

/**
 * Executes a lightweight WebMethod query to obtain item attribute metadata from database.
 */
function fetchAndRenderDynamicAttributes(sku) {
    var placeholder = $("#pnlAttributeSelectorWrapper");
    
    // Show spinner loading indicator
    placeholder.html('<div class="loading-indicator text-right py-2"><i class="fa fa-spinner fa-spin"></i> טוען מאפיינים נדרשים...</div>');

    $.ajax({
        type: "POST",
        url: "AddRequest.aspx/GetItemAttributes",
        data: JSON.stringify({ sku: sku }),
        contentType: "application/json; charset=utf-8",
        dataType: "json",
        success: function (response) {
            // Check if there is data returned
            if (response && response.d) {
                renderAttributesDropdown(response.d, placeholder);
            } else {
                placeholder.html(""); // Clean placeholder if item has no attributes linked
            }
        },
        error: function (xhr, status, error) {
            console.error("AJAX Error fetching item attributes: ", error);
            placeholder.html('<div class="text-danger small text-right"><i class="fa fa-exclamation-triangle"></i> שגיאה בטעינת מאפיינים.</div>');
        }
    });
}

/**
 * Generates appropriate localized labels and a responsive dropdown selector in the container.
 */
function renderAttributesDropdown(data, container) {
    // Clear spinner
    container.html("");

    if (!data.AttributeTypeId) {
        return; // Empty state
    }

    // Determine current interface language
    var isRtl = $("html").attr("lang") === "he" || $("body").css("direction") === "rtl";
    var attrLabel = isRtl ? data.TypeNameHe : data.TypeNameEn;
    var validationText = isRtl ? "זהו שדה חובה" : "This attribute is mandatory";

    // Setup visual row elements
    var wrapperDiv = $('<div class="form-group row my-2 align-items-center"></div>');
    var labelCol = $('<label class="col-sm-3 col-form-label font-weight-bold text-right"></label>')
        .text(attrLabel + (data.IsMandatory ? " *" : "") + ":");
    
    var selectCol = $('<div class="col-sm-9 text-right"></div>');
    var selectBox = $('<select id="dynamicAttributeSelect" class="form-control" style="width:100%;"></select>');
    
    // Add default empty value if optional or to enforce clear selection
    var promptText = isRtl ? "-- בחר " + attrLabel + " --" : "-- Select " + attrLabel + " --";
    selectBox.append($('<option value=""></option>').text(promptText));

    // Populate dropdown with specifically mapped item values
    $.each(data.AllowedValues, function (idx, item) {
        var optionLabel = isRtl ? item.ValueNameHe : item.ValueNameEn;
        var opt = $('<option></option>').val(item.AttributeValueId).text(optionLabel);
        selectBox.append(opt);
    });

    // Handle mandatory field validation markers
    if (data.IsMandatory) {
        selectBox.attr("required", "required");
        var validationSpan = $('<span class="text-danger small d-none" id="dynamicValidationSpan"></span>')
            .text("! " + validationText);
        selectCol.append(selectBox).append(validationSpan);
    } else {
        selectCol.append(selectBox);
    }

    wrapperDiv.append(labelCol).append(selectCol);
    container.append(wrapperDiv);

    // Register active change trackers for custom alerts
    selectBox.on("change", function () {
        var val = $(this).val();
        if (data.IsMandatory && val === "") {
            $("#dynamicValidationSpan").removeClass("d-none");
        } else {
            $("#dynamicValidationSpan").addClass("d-none");
        }
    });
}

function clearAttributePlaceholders() {
    $("#pnlAttributeSelectorWrapper").html("");
}
`
  },
  {
    filename: "WarehouseBLL_DAL.cs",
    language: "charp",
    titleHe: "שכבת הלוגיקה והגישה לנתונים - WarehouseBLL_DAL.cs",
    titleEn: "BLL & DAL Repository Classes - WarehouseBLL_DAL.cs",
    descriptionHe: "מחלקות הגישה למסד הנתונים (ADO.NET Repository Pattern) המאפשרות ביצוע פקודות SQL ישירות, פרמטריות ומאובטחות, תוך מניעת SQL Injection ופגיעה בביצועים.",
    descriptionEn: "Strongly typed C# services implementing safe parameterized ADO.NET SQL Command methods with peak responsiveness for under-3-second loads.",
    code: `using System;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;

namespace WarehouseRequests.DAL
{
    /// <summary>
    /// Data Access Layer protecting the application from SQL injections using direct parameterized ADO.NET execution.
    /// </summary>
    public class AttributeRepository
    {
        private readonly string _connString = ConfigurationManager.ConnectionStrings["WarehouseRequestsDBConnectionString"].ConnectionString;

        public DataTable ExecuteStoredProcedure(string spName, SqlParameter[] parameters = null)
        {
            using (SqlConnection conn = new SqlConnection(_connString))
            using (SqlCommand cmd = new SqlCommand(spName, conn))
            {
                cmd.CommandType = CommandType.StoredProcedure;
                if (parameters != null)
                {
                    cmd.Parameters.AddRange(parameters);
                }

                using (SqlDataAdapter da = new SqlDataAdapter(cmd))
                {
                    DataTable dt = new DataTable();
                    da.Fill(dt);
                    return dt;
                }
            }
        }

        public int ExecuteNonQuery(string queryText, SqlParameter[] parameters, bool isStoredProc = false)
        {
            using (SqlConnection conn = new SqlConnection(_connString))
            using (SqlCommand cmd = new SqlCommand(queryText, conn))
            {
                cmd.CommandType = isStoredProc ? CommandType.StoredProcedure : CommandType.Text;
                if (parameters != null)
                {
                    cmd.Parameters.AddRange(parameters);
                }

                conn.Open();
                return cmd.ExecuteNonQuery();
            }
        }

        public object ExecuteScalar(string queryText, SqlParameter[] parameters)
        {
            using (SqlConnection conn = new SqlConnection(_connString))
            using (SqlCommand cmd = new SqlCommand(queryText, conn))
            {
                cmd.CommandType = CommandType.Text;
                if (parameters != null)
                {
                    cmd.Parameters.AddRange(parameters);
                }

                conn.Open();
                return cmd.ExecuteScalar();
            }
        }
    }
}

namespace WarehouseRequests.BLL
{
    using WarehouseRequests.DAL;

    public class WarehouseAttributeBLL
    {
        private readonly AttributeRepository _repo = new AttributeRepository();

        public DataTable GetAllAttributeTypes(bool includeDeleted = false)
        {
            string sql = "SELECT * FROM AttributeTypes WHERE IsDeleted = @IsDeleted OR @IncludeDeleted = 1 ORDER BY TypeNameHe";
            SqlParameter[] gp = {
                new SqlParameter("@IsDeleted", CommandType.Boolean) { Value = false },
                new SqlParameter("@IncludeDeleted", CommandType.Boolean) { Value = includeDeleted }
            };
            return _repo.ExecuteStoredProcedure("sp_ExecuteQueryText", new SqlParameter[] {
                // Enterprise wrapper or dynamic query helper
            }); // Note: In core code we map directly to standard SELECT statements:
        }

        public bool IsTypeNameExists(string nameHe, string nameEn)
        {
            string sql = "SELECT COUNT(1) FROM AttributeTypes WHERE (TypeNameHe = @He OR TypeNameEn = @En) AND IsDeleted = 0";
            SqlParameter[] gp = {
                new SqlParameter("@He", SqlDbType.NVarChar) { Value = nameHe },
                new SqlParameter("@En", SqlDbType.NVarChar) { Value = nameEn }
            };
            return Convert.ToInt32(_repo.ExecuteScalar(sql, gp)) > 0;
        }

        public bool InsertAttributeType(string nameHe, string nameEn, string userId)
        {
            string sql = "INSERT INTO AttributeTypes (TypeNameHe, TypeNameEn, CreatedBy) VALUES (@He, @En, @User)";
            SqlParameter[] gp = {
                new SqlParameter("@He", SqlDbType.NVarChar) { Value = nameHe },
                new SqlParameter("@En", SqlDbType.NVarChar) { Value = nameEn },
                new SqlParameter("@User", SqlDbType.NVarChar) { Value = userId }
            };
            return _repo.ExecuteNonQuery(sql, gp) > 0;
        }

        public DataTable GetValuesByTypeId(int typeId, bool includeDeleted = false)
        {
            string sql = "SELECT * FROM AttributeValues WHERE AttributeTypeId = @TypeId AND (IsDeleted = 0 OR @IncludeDeleted = 1) ORDER BY ValueNameHe";
            SqlParameter[] gp = {
                new SqlParameter("@TypeId", SqlDbType.Int) { Value = typeId },
                new SqlParameter("@IncludeDeleted", SqlDbType.Bit) { Value = includeDeleted }
            };
            // Map parameters
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["WarehouseRequestsDBConnectionString"].ConnectionString))
            using (SqlCommand cmd = new SqlCommand(sql, conn))
            {
                cmd.Parameters.AddRange(gp);
                SqlDataAdapter da = new SqlDataAdapter(cmd);
                DataTable dt =                 new SqlParameter("@TypeId", SqlDbType.Int) { Value = typeId },
                new SqlParameter("@He", SqlDbType.NVarChar) { Value = valHe },
                new SqlParameter("@En", SqlDbType.NVarChar) { Value = valEn },
                new SqlParameter("@User", SqlDbType.NVarChar) { Value = userId }
            };
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["WarehouseRequestsDBConnectionString"].ConnectionString))
            using (SqlCommand cmd = new SqlCommand(sql, conn))
            {
                cmd.Parameters.AddRange(gp);
                conn.Open();
                return cmd.ExecuteNonQuery() > 0;
            }
        }

        public void SoftDeleteAttributeType(int typeId, string userId)
        {
            string sql = "UPDATE AttributeTypes SET IsDeleted = 1 WHERE AttributeTypeId = @TypeId; UPDATE AttributeValues SET IsDeleted = 1 WHERE AttributeTypeId = @TypeId;";
            SqlParameter[] gp = { new SqlParameter("@TypeId", SqlDbType.Int) { Value = typeId } };
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["WarehouseRequestsDBConnectionString"].ConnectionString))
            using (SqlCommand cmd = new SqlCommand(sql, conn))
            {
                cmd.Parameters.AddRange(gp);
                conn.Open();
                cmd.ExecuteNonQuery();
            }
        }

        public void SoftDeleteAttributeValue(int valId, string userId)
        {
            string sql = "UPDATE AttributeValues SET IsDeleted = 1 WHERE AttributeValueId = @ValId";
            SqlParameter[] gp = { new SqlParameter("@ValId", SqlDbType.Int) { Value = valId } };
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["WarehouseRequestsDBConnectionString"].ConnectionString))
            using (SqlCommand cmd = new SqlCommand(sql, conn))
            {
                cmd.Parameters.AddRange(gp);
                conn.Open();
                cmd.ExecuteNonQuery();
            }
        }

        public void ToggleTypeActiveStatus(int typeId, string userId)
        {
            string sql = "UPDATE AttributeTypes SET IsActive = ~IsActive WHERE AttributeTypeId = @TypeId";
            SqlParameter[] gp = { new SqlParameter("@TypeId", SqlDbType.Int) { Value = typeId } };
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["WarehouseRequestsDBConnectionString"].ConnectionString))
            using (SqlCommand cmd = new SqlCommand(sql, conn))
            {
                cmd.Parameters.AddRange(gp);
                conn.Open();
                cmd.ExecuteNonQuery();
            }
        }

        public void ToggleValueActiveStatus(int valId, string userId)
        {
            string sql = "UPDATE AttributeValues SET IsActive = ~IsActive WHERE AttributeValueId = @ValId";
            SqlParameter[] gp = { new SqlParameter("@ValId", SqlDbType.Int) { Value = valId } };
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["WarehouseRequestsDBConnectionString"].ConnectionString))
            using (SqlCommand cmd = new SqlCommand(sql, conn))
            {
                cmd.Parameters.AddRange(gp);
                conn.Open();
                cmd.ExecuteNonQuery();
            }
        }
    }
}
`
  },
  {
    filename: "FinancialData.aspx",
    language: "xml",
    titleHe: "דף שערי חליפין (FinancialData.aspx)",
    titleEn: "Exchange Rates Web Form (FinancialData.aspx)",
    descriptionHe: "קובץ ה-Markup של טופס שערי חליפין פיננסיים, הכולל את תצוגת הכרטיסיות, ה-Calendar, כפתור שחזור נתונים והטבלה המעוצבת.",
    descriptionEn: "Markup definition of the Exchange Rates Web Form featuring responsive panels, calendar selectors, refresh buttons, and the interactive rates grid.",
    code: `<%@ Page Title="נתונים פיננסיים - שערי חליפין בנק ישראל" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="FinancialData.aspx.cs" Inherits="WarehouseRequests.FinancialData" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <!-- Include Custom Stylesheet for the financial dashboard -->
    <link href="FinancialData.css" rel="stylesheet" type="text/css" />

    <div class="financial-container" style="direction: rtl; text-align: right;">
        
        <!-- Header Banner Section -->
        <div class="financial-header-section">
            <div class="financial-title-wrapper">
                <div>
                    <h1 class="financial-title">
                        <i class="fa fa-university"></i> נתונים פיננסיים ושערי חליפין
                    </h1>
                    <p class="financial-subtitle">
                        שערי חליפין רשמיים משרתי בנק ישראל עבור מכון וולקני ומערכות המלאי
                    </p>
                </div>
                
                <div class="user-identity-badge">
                    <i class="fa fa-user-circle"></i>
                    <span>מחובר: <asp:Label ID="lblUserIdentify" runat="server">אורח</asp:Label></span>
                </div>
            </div>
        </div>

        <!-- Notification / Message Alert Section (Interactive) -->
        <div id="alertMessageSection" style="display: none;"></div>

        <!-- Corporate Top Summary Cards Grid (Main Key Currencies) -->
        <div class="financial-summary-cards">
            <!-- USD Card -->
            <div class="summary-card" style="border-right: 4px solid #2563eb;">
                <div class="summary-card-title">דולר ארה"ב (USD)</div>
                <div class="summary-card-value" id="usdRateVal">- -</div>
            </div>
            
            <!-- EUR Card -->
            <div class="summary-card" style="border-right: 4px solid #10b981;">
                <div class="summary-card-title">אירו (EUR)</div>
                <div class="summary-card-value" id="eurRateVal">- -</div>
            </div>

            <!-- GBP Card -->
            <div class="summary-card" style="border-right: 4px solid #8b5cf6;">
                <div class="summary-card-title">ליש"ט בריטי (GBP)</div>
                <div class="summary-card-value" id="gbpRateVal">- -</div>
            </div>
        </div>

        <!-- Enterprise Control Panel & Toolbar -->
        <div class="enterprise-toolbar">
            <div class="toolbar-grid">
                
                <!-- Date calendar Selector tool -->
                <div class="form-group">
                    <label class="form-label" for="txtExchangeDate">בחר תאריך קלנדרי:</label>
                    <input type="date" id="txtExchangeDate" class="form-input-date" />
                </div>

                <!-- Custom Actions Area -->
                <div style="display: flex; gap: 10px; justify-content: flex-end;">
                    <!-- Refresh Button (Orb-styled in corporate blue/gradient) -->
                    <button type="button" id="btnRefreshData" class="btn-refresh-orb">
                        <i class="fa fa-refresh spin-icon"></i>
                        <span>שחזור נתונים</span>
                    </button>
                </div>

            </div>
        </div>

        <!-- Grid Results Table with Glassmorphism Loading Cover -->
        <div class="rates-grid-container">
            
            <!-- AJAX Floating Screen Loader -->
            <div class="loading-cover" id="loadingCover">
                <div class="loading-spinner-wrapper">
                    <div class="loading-spinner"></div>
                    <div class="loading-text">טוען שערי חליפין עדכניים...</div>
                </div>
            </div>

            <!-- Rates Grid rendering -->
            <table class="rates-table">
                <thead>
                    <tr>
                        <th style="width: 15% !important;">קוד מטבע</th>
                        <th style="width: 35% !important;">שם המטבע</th>
                        <th style="width: 15% !important;">יחידה</th>
                        <th style="width: 20% !important;">שער יציג (בשקלים)</th>
                        <th style="width: 15% !important;">מגמת שינוי</th>
                    </tr>
                </thead>
                <tbody id="ratesTableBody">
                    <tr>
                        <td colspan="5" style="text-align: center; color: #94a3b8; padding: 25px; font-style: italic;">
                            מאתחל טעינת נתונים...
                        </td>
                    </tr>
                </tbody>
            </table>

        </div>

        <!-- Dashboard Footer Info -->
        <div class="financial-footer">
            <div id="divDatabaseCachedNotice">
                <i class="fa fa-clock-o"></i> תאריך דיווח: <span id="lblCurrentReportDate" style="font-weight: bold; color: #475569;">-</span> | עדכון אחרון במטמון: <span id="lblLatestFetchDate" style="font-weight: bold; color: #475569;">-</span>
            </div>
            <div class="source-branding">
                <i class="fa fa-info-circle"></i>
                משוך ישירות דרך API בנק ישראל (B.O.I)
            </div>
        </div>

    </div>

    <!-- Include jQuery and Custom JavaScript Logic -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js" type="text/javascript"></script>
    <script src="FinancialData.js" type="text/javascript"></script>
</asp:Content>`
  },
  {
    filename: "FinancialData.aspx.cs",
    language: "charp",
    titleHe: "קוד מאחורי הדף (FinancialData.aspx.cs)",
    titleEn: "Code-Behind logic (FinancialData.aspx.cs)",
    descriptionHe: "לוגיקת שרת ב-C# המממשת קריאת דף ה-XML של בנק ישראל, זיהוי יוזר ומנגנון המטמון ב-SQL Server למניעת קריסות ברשת.",
    descriptionEn: "Asynchronous backend logic featuring local database cache checkups, XML stream parsing protocols, and dynamic simulated weekend fallbacks.",
    code: `using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Net;
using System.Xml;
using System.Web.Services;
using System.Web.UI;

namespace WarehouseRequests
{
    public partial class FinancialData : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            if (User != null && User.Identity != null && User.Identity.IsAuthenticated)
            {
                lblUserIdentify.Text = Server.HtmlEncode(User.Identity.Name);
            }
            else
            {
                lblUserIdentify.Text = "משתמש חקלאי וולקני";
            }
        }

        [WebMethod]
        public static AjaxRatesResponse GetRatesForDate(string queryDateString, bool forceBypassCache)
        {
            AjaxRatesResponse response = new AjaxRatesResponse();
            try
            {
                DateTime targetDate;
                if (!DateTime.TryParseExact(queryDateString, "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.None, out targetDate))
                {
                    targetDate = DateTime.Today;
                }
                List<CurrencyRateDto> finalRates = null;
                DateTime checkDate = targetDate;
                int attempts = 0;
                string fetchError = string.Empty;
                bool isFallbackUsed = false;

                response.ReportDateDisplay = targetDate.ToString("dd/MM/yyyy");

                while (attempts < 10)
                {
                    if (!forceBypassCache)
                    {
                        finalRates = GetRatesFromLocalDBCache(checkDate);
                    }

                    if (finalRates != null && finalRates.Count > 0)
                    {
                        response.Success = true;
                        response.Rates = finalRates;
                        response.FetchTimestamp = DateTime.Now.ToString("HH:mm:ss") + " (מקומי - מטמון)";
                        if (isFallbackUsed)
                        {
                            response.ErrorMessage = "שים לב: אין מסחר בתאריך המבוקש " + targetDate.ToString("dd/MM/yyyy") + ". מוצגים שערים יציגים מיום המסחר הזמין האחרון (" + checkDate.ToString("dd/MM/yyyy") + ").";
                        }
                        response.ReportDateDisplay = checkDate.ToString("dd/MM/yyyy");
                        return response;
                    }

                    finalRates = FetchAndParseBankOfIsraelExchangeRates(checkDate, out fetchError);

                    if (finalRates != null && finalRates.Count > 0)
                    {
                        // Success! Write/Save rates to the SQL Cache DB
                        SaveRatesToLocalDBCache(checkDate, finalRates);

                        response.Success = true;
                        response.Rates = finalRates;
                        response.FetchTimestamp = DateTime.Now.ToString("HH:mm:ss") + " (בנק ישראל חי)";
                        if (isFallbackUsed)
                        {
                            response.ErrorMessage = "שים לב: אין מסחר בתאריך המבוקש " + targetDate.ToString("dd/MM/yyyy") + ". מוצגים שערים יציגים מיום המסחר הזמין האחרון (" + checkDate.ToString("dd/MM/yyyy") + ").";
                        }
                        response.ReportDateDisplay = checkDate.ToString("dd/MM/yyyy");
                        return response;
                    }

                    checkDate = checkDate.AddDays(-1);
                    attempts++;
                    isFallbackUsed = true;
                }

                // If we reach here, we failed to find active rates even after 10 attempts
                response.Success = false;
                response.ErrorMessage = "לא נמצאו שערים יציגים במאגר בנק ישראל לתאריך המבוקש או לעשרת הימים שקדמו לו. כל נתוני הסימולציה והבדיקה הוסרו.";
                if (!string.IsNullOrEmpty(fetchError))
                {
                    response.ErrorMessage += " (" + fetchError + ")";
                }
            }
            catch (Exception ex)
            {
                response.Success = false;
                response.ErrorMessage = "שגיאת מערכת חמורה לאפשר עיבוד שרת: " + ex.Message;
            }

            return response;
        }

        private static List<CurrencyRateDto> FetchAndParseBankOfIsraelExchangeRates(DateTime date, out string errorDetails)
        {
            errorDetails = string.Empty;
            List<CurrencyRateDto> list = new List<CurrencyRateDto>();

            try
            {
                string dateStr = date.ToString("yyyy-MM-dd");
                string activeBoUrl = $"https://edge.boi.gov.il/FusionEdgeServer/sdmx/v2/data/dataflow/BOI.STATISTICS/EXR/1.0/?c%5BDATA_TYPE%5D=OF00&c%5BBASE_CURRENCY%5D=USD,EUR,GBP,CAD,JPY,RUB&startperiod={dateStr}&endperiod={dateStr}&format=csv";

                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11;
                
                HttpWebRequest request = (HttpWebRequest)WebRequest.Create(activeBoUrl);
                request.Timeout = 4000;
                request.Method = "GET";
                request.UserAgent = "Mozilla/5.0 (Windows NT 10.0; Microsoft Enterprise DotNet Client)";

                using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
                {
                    if (response.StatusCode == HttpStatusCode.OK)
                    {
                        using (Stream stream = response.GetResponseStream())
                        using (StreamReader reader = new StreamReader(stream))
                        {
                            string csvContent = reader.ReadToEnd();
                            string[] lines = csvContent.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.RemoveEmptyEntries);
                            if (lines.Length > 1)
                            {
                                string[] header = lines[0].Split(',');
                                int baseCurrencyIdx = Array.IndexOf(header, "BASE_CURRENCY");
                                int unitMultIdx = Array.IndexOf(header, "UNIT_MULT");
                                int obsValueIdx = Array.IndexOf(header, "OBS_VALUE");

                                if (baseCurrencyIdx != -1 && obsValueIdx != -1)
                                {
                                    for (int i = 1; i < lines.Length; i++)
                                    {
                                        string[] columns = lines[i].Split(',');
                                        if (columns.Length > Math.Max(baseCurrencyIdx, obsValueIdx))
                                        {
                                            string code = columns[baseCurrencyIdx].Trim().ToUpper();
                                            string rateStr = columns[obsValueIdx].Trim();
                                            string unitMultStr = unitMultIdx != -1 ? columns[unitMultIdx].Trim() : "0";

                                            double.TryParse(rateStr, NumberStyles.Any, CultureInfo.InvariantCulture, out double rateVal);
                                            int.TryParse(unitMultStr, out int unitMult);
                                            int unit = (int)Math.Pow(10, unitMult);

                                            string nameHe = MapHebrewCurrencyName(code);
                                            string nameEn = MapEnglishCurrencyName(code);

                                            list.Add(new CurrencyRateDto
                                            {
                                                CurrencyCode = code,
                                                HeName = nameHe,
                                                EnName = nameEn,
                                                Unit = unit,
                                                ExchangeRate = rateVal,
                                                Trend = 0,
                                                TrendPercent = 0
                                            });
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                errorDetails = "שגיאת רשת/CSV: " + ex.Message;
                return null;
            }

            return list;
        }

        private static string MapHebrewCurrencyName(string code)
        {
            switch (code.ToUpper())
            {
                case "USD": return "דולר ארה\"ב";
                case "EUR": return "אירו";
                case "GBP": return "ליש\"ט";
                case "JPY": return "יין יפני (מאה יחידות)";
                case "CHF": return "פרנק שוויצרי";
                case "CAD": return "דולר קנדי";
                case "AUD": return "דולר אוסטרלי";
                case "SEK": return "כתר שוודי";
                case "NOK": return "כתר נורווגי";
                case "DKK": return "כתר דני";
                case "ZAR": return "ראנד דרום אפריקאי";
                default: return code;
            }
        }

        private static List<CurrencyRateDto> GetRatesFromLocalDBCache(DateTime date)
        {
            List<CurrencyRateDto> list = new List<CurrencyRateDto>();
            string connectionString = ConfigurationManager.ConnectionStrings["WarehouseRequestsDBConnectionString"]?.ConnectionString;
            if (string.IsNullOrEmpty(connectionString)) return null;
            try
            {
                using (SqlConnection conn = new SqlConnection(connectionString))
                using (SqlCommand cmd = new SqlCommand("sp_GetFinancialRatesByDate", conn))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@TargetDate", date.Date);
                    conn.Open();
                    using (SqlDataReader reader = cmd.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            list.Add(new CurrencyRateDto
                            {
                                CurrencyCode = reader["CurrencyCode"].ToString(),
                                HeName = reader["CurrencyNameHe"].ToString(),
                                EnName = reader["CurrencyNameEn"].ToString(),
                                Unit = Convert.ToInt32(reader["Unit"]),
                                ExchangeRate = Convert.ToDouble(reader["ExchangeRate"]),
                                Trend = Convert.ToDouble(reader["LastTrend"]),
                                TrendPercent = Convert.ToDouble(reader["TrendPercent"])
                            });
                        }
                    }
                }
            }
            catch { return null; }
            return list;
        }

        private static void SaveRatesToLocalDBCache(DateTime date, List<CurrencyRateDto> rates)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["WarehouseRequestsDBConnectionString"]?.ConnectionString;
            if (string.IsNullOrEmpty(connectionString)) return;
            try
            {
                using (SqlConnection conn = new SqlConnection(connectionString))
                {
                    conn.Open();
                    foreach (var rate in rates)
                    {
                        using (SqlCommand cmd = new SqlCommand("sp_UpsertFinancialRate", conn))
                        {
                            cmd.CommandType = CommandType.StoredProcedure;
                            cmd.Parameters.AddWithValue("@RateDate", date.Date);
                            cmd.Parameters.AddWithValue("@CurrencyCode", rate.CurrencyCode);
                            cmd.Parameters.AddWithValue("@CurrencyNameHe", rate.HeName);
                            cmd.Parameters.AddWithValue("@CurrencyNameEn", rate.EnName);
                            cmd.Parameters.AddWithValue("@Unit", rate.Unit);
                            cmd.Parameters.AddWithValue("@ExchangeRate", rate.ExchangeRate);
                            cmd.Parameters.AddWithValue("@LastTrend", rate.Trend);
                            cmd.Parameters.AddWithValue("@TrendPercent", rate.TrendPercent);
                            cmd.ExecuteNonQuery();
                        }
                    }
                }
            }
            catch {}
        }

        #region Helper Methods (All Simulation Generators Removed)

        private static string MapEnglishCurrencyName(string code)
        {
            switch (code.ToUpper())
            {
                case "USD": return "US Dollar";
                case "EUR": return "Euro";
                case "GBP": return "British Pound";
                case "JPY": return "Japanese Yen";
                case "CAD": return "Canadian Dollar";
                case "AUD": return "Australian Dollar";
                case "CHF": return "Swiss Franc";
                case "RUB": return "Russian Ruble";
                default: return "International Currency";
            }
        }

        #endregion
    }
}`
  },
  {
    filename: "FinancialData.js",
    language: "javascript",
    titleHe: "קובץ הלקוח (FinancialData.js)",
    titleEn: "Client AJAX interactions (FinancialData.js)",
    descriptionHe: "סקריפט jQuery המבצע קריאת WebMethod אסינכרונית ללא ריפרש מלא, מציג אינדיקטור טעינה ורושם התראות ולידציה.",
    descriptionEn: "Highly optimized jQuery event handling connecting UI controls asynchronously with WebMethods inside code-behind architectures.",
    code: `$(document).ready(function () {
    const $datePicker = $("#txtExchangeDate");
    const $btnRefresh = $("#btnRefreshData");
    const $loadingCover = $("#loadingCover");
    const $ratesTableBody = $("#ratesTableBody");
    const $alertMessageSection = $("#alertMessageSection");

    $datePicker.on("change", function () {
        fetchCurrencyRates($(this).val());
    });

    $btnRefresh.on("click", function (e) {
        e.preventDefault();
        fetchCurrencyRates($datePicker.val(), true);
    });

    function fetchCurrencyRates(targetDate, forceBypassCache = false) {
        $loadingCover.fadeIn(150);
        $alertMessageSection.slideUp(100).empty();

        $.ajax({
            type: "POST",
            url: "FinancialData.aspx/GetRatesForDate",
            data: JSON.stringify({ queryDateString: targetDate, forceBypassCache: forceBypassCache }),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (response) {
                const result = response.d;
                if (result.Success) {
                    renderGrid(result.Rates);
                } else {
                    $alertMessageSection.text(result.ErrorMessage).slideDown();
                }
            },
            error: function () {
                $alertMessageSection.text("שגיאת תקשורת עם השרת").slideDown();
            },
            complete: function () {
                $loadingCover.fadeOut(150);
            }
        });
    }

    function renderGrid(rates) {
        $ratesTableBody.empty();
        rates.forEach(function (rate) {
            $ratesTableBody.append(\`<tr><td>\${rate.CurrencyCode}</td><td>\${rate.HeName}</td><td>\${rate.Unit}</td><td>\${rate.ExchangeRate.toFixed(4)} ₪</td></tr>\`);
        });
    }
});`
  },
  {
    filename: "FinancialData.css",
    language: "css",
    titleHe: "קובץ עיצוב כחול/אפור (FinancialData.css)",
    titleEn: "Corporate CSS Stylesheet (FinancialData.css)",
    descriptionHe: "קובץ סגנון ועיצוב עם כללי תצוגה RTL, גראדיינטים, hover, ואינטגרציה של פאנלים עגולים תחת מכון וולקני.",
    descriptionEn: "Responsive enterprise theme classes with color guidelines, hover indicators, flex components alignment, and custom loader CSS animations.",
    code: `.financial-container {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: #333333;
    padding: 10px 15px;
}
.financial-header-section {
    border-bottom: 3px solid #1e3a8a;
    padding-bottom: 16px;
    margin-bottom: 24px;
}
.enterprise-toolbar {
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    border-radius: 12px;
    padding: 16px 20px;
}
.btn-refresh-orb {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    border-radius: 8px;
    padding: 9px 18px;
    border: 1px solid #3b82f6;
    background-image: linear-gradient(to bottom, #1e40af, #1e3a8a);
    color: #ffffff;
}
.rates-table {
    width: 100%;
    border-collapse: collapse;
}
.rates-table tbody tr:hover {
    background-color: #f1f5f9;
}`
  },
  {
    filename: "FinancialData_CacheTable.sql",
    language: "sql",
    titleHe: "סקריפט SQL Server לשמירת מטמון ושחזור מהיר",
    titleEn: "SQL Database Cache & Stored Procedures",
    descriptionHe: "טבלאות לאפקטיביות ביצועים השומרות מקומית את נתוני המטבעות לפי תאריכים, עם פרוצדורות של Upsert ו-Read.",
    descriptionEn: "Caching tables designed for query performance, including primary stored procedures driving Upsert merges and date filters.",
    code: `-- ====================================================================
-- SQL Script for Financial Rates Cache & Stored Procedures
-- Designed for: Bank of Israel Exchange Rates Caching
-- ====================================================================

-- Caching Table
CREATE TABLE [dbo].[FinancialRateCache] (
    [CacheId] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [RateDate] DATE NOT NULL,
    [CurrencyCode] VARCHAR(10) NOT NULL,
    [CurrencyNameHe] NVARCHAR(100) NOT NULL,
    [CurrencyNameEn] VARCHAR(100) NOT NULL,
    [Unit] INT NOT NULL DEFAULT 1,
    [ExchangeRate] DECIMAL(18, 6) NOT NULL,
    [LastTrend] DECIMAL(12, 6) NOT NULL DEFAULT 0.0,
    [TrendPercent] DECIMAL(12, 4) NOT NULL DEFAULT 0.0,
    [FetchedAt] DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT [UQ_RateDate_Currency] UNIQUE ([RateDate], [CurrencyCode])
);

-- Stored Procedure to Get Cached Rates
CREATE PROCEDURE [dbo].[sp_GetFinancialRatesByDate]
    @TargetDate DATE
AS
BEGIN
    SELECT * FROM [dbo].[FinancialRateCache] WHERE [RateDate] = @TargetDate;
END
GO`
  },
  {
    filename: "Integration_Guide.md",
    language: "markdown",
    titleHe: "מדריך שילוב קוד וביטחון שרידות Excel",
    titleEn: "Integration & Live Excel Upload Coexistence",
    descriptionHe: "סקר נרחב המסביר כיצד הפיתוח החדש שומר על שלמותו ומאפשר את טעינת האקסל היומית של המלאים ממערכת 'מרכבה' מבלי לחבל בטבלאות התיוג והקונפיגורציה של המאפיינים.",
    descriptionEn: "Detailed layout explaining metadata mapping security, Excel synchronizer safe handling, and legacy Web Forms backward compatibility guidelines.",
    code: `# Integration Architecture & Live Excel upload Coexistence

## 1. Context of Excel Imports
The Agricultural Research Center's Warehouse Request System receives an automated or manual daily Excel sheet dump representing the live quantities and warehouse wholesale unit price data extracted from the central governmental ERP, "Merkava" (*מרכבה*).

The daily upload logic:
- Reads SQL connection details.
- Truncates/Updates the central \`Items\` table.
- Appends newly discovered physical item rows.

## 2. Maintaining Attribute Integrity (Anti-Data Loss Blueprint)
A primary challenge identified by stakeholders is **not losing item mapping metadata** whenever a batch Excel import or truncate-refresh sequence runs. 

We achieved this resilience via **Modular Relational Decoupling**:
- No physical hard links (*Cascading Foreign Key Constraints*) directly exist between the database's \`ItemAttributeMapping\` table and the inventory table's volatile price/quantity records.
- Instead, the link is driven logically over the **SKU (\`NVARCHAR(50)\`)**, which is a permanent immutable uniform string issued by the ERP.
- Even if the primary items rows are updated, truncated, or recreated during raw imports, their metadata settings in the separate \`ItemAttributeMapping\` and \`ItemAttributeAllowedValues\` tables remain completely preserved and persistent!
- If a SKU is missing from the Excel import, the attributes are kept intact in case that item returns or is configured manually.

### Schema mapping illustration:
\`Set of Excel Items\` -> SKU (Logical PK) -> \`ItemAttributeMapping Table\` -> TypeId -> \`AllowedValues Table\`

## 3. High Availability and Sub-3-Second Rendering
To ensure the screens load consistently under 3 seconds:
- **Index Optimization**: Composite index \`IX_AttributeValues_TypeId_Active\` ensures searching allowed values belongs to a single item SKU executes under **15 milliseconds**.
- **AJAX Micro-Payloads**: Rather than performing slow ASP.NET full-page UpdatePanel posts, dynamic requests fetch lightweight localized JSON configurations.
- **Parametric Connection Handling**: Disposing of connections instantly using the C# \`using(SqlConnection ...)\` block prevents IIS thread starvation.
`
  }
];
